#!/bin/bash
#
# git-browse, v0.1.2
# Author: Nick Sawyer <nick@nicksawyer.net>
#
# This script allows developers to easily open the web view of files and directories
# from their local Git repositories in a browser, making it a breeze to share code
# with co-workers.  The script currently supports GitHub and custom Stash installs.
# See "showUsage" function for invocation details.
#
###############################################################################

function showUsage {
    echo
    echo "USAGE: git-browse [--url-only] [--ref=<head-reference>] [ [--commits] | [<path>] [--line=<line>] ]"
    echo
    echo "Running the script with no arguments will open the web view of the current"
    echo "directory in your browser at the currently checked out branch/tag/commit."
    echo "You can use the '--ref' argument to specify the branch/tag/commit of your"
    echo "choice if you don't want to use the current one."
    echo
    echo "You can optionally pass in any ONE of the following:"
    echo "    A specific commit hash to show"
    echo "    The relative path to a file or a directory in the repository to go to directly"
    echo "    The '--commits' flag, which switches to commit listing mode"
    echo
    echo "Note: If you're passing a file path and you want to point to a particular line"
    echo "in the file, use the '--line' argument."
    echo
    echo "Using the '--url-only' flag will execute the script the same way, but only"
    echo "display the URL without opening it in your browser."
    echo

    exit 1
}

# Default to opening the URL in a browser
URL_ONLY=false
# Internal variable to keep track of mode; can be "browse" or "commits"
_MODE="browse"
# Internal variable to keep track of the type of target set; can be "empty", "commit", "file", or "directory"
_TARGET_TYPE="empty"

# Load config file if it exists
CONF="$HOME/.gitbrowse"
if [[ -e $CONF ]]; then
    source $CONF
fi

# Set Stash hostname info for tests
if [[ $TEST_STASH_HOSTNAME != "" ]]; then
    STASH_HOSTNAME=$TEST_STASH_HOSTNAME
    STASH_URL_ROOT=$TEST_STASH_URL_ROOT
fi

# Make sure we're in a Git repository, and get the origin remote URL
ORIGIN=$(git remote -v 2>/dev/null | grep -m 1 origin | awk '{print $2}')
if [[ $ORIGIN == "" ]]; then
    # Abort if this isn't a Git repository
    echo "Not a Git repository; aborting"
    exit 65
elif [[ $ORIGIN == *github.com* ]]; then
    REMOTE_SERVICE="github"
elif [[ $ORIGIN == *$STASH_HOSTNAME* ]]; then
    REMOTE_SERVICE="stash"
else
    echo "Unable to handle origin URL '$ORIGIN'; aborting"
    exit 65
fi

# Parse the origin URL to get the parts we need
# We can handle the following formats:
#     git@github.com:symfony/symfony.git
#     https://github.com/symfony/symfony.git
#     ssh://git@stash.mycompany.com:8080/PROJ/repository.git
#     https://username@stash.mycompany.com/stash/scm/proj/repository.git
if [[ $ORIGIN =~ .*[:\/]{1}([A-Za-z]+)\/([A-Za-z]+).git$ ]]; then
    GROUP=${BASH_REMATCH[1]}
    REPO=${BASH_REMATCH[2]}
else
    echo "Unable to handle origin URL '$ORIGIN'; aborting"
    exit 65
fi

# Parse command line arguments
for arg in "$@"; do
    case $arg in
        --commits)
        _MODE="commits"
        shift
        ;;
        --url-only)
        URL_ONLY=true
        shift
        ;;
        --ref=*)
        REF="${arg#*=}"
        shift
        ;;
        --line=*)
        LINE="${arg#*=}"
        shift
        ;;
        --help)
        showUsage
        ;;
        *)
        # Assume that this is a commit hash reference, or the relative path to
        # a file or directory; we'll verify after the arg loop
        TARGET=$arg
        shift
        ;;
    esac
done

# Verify target arg
if [[ $TARGET != "" ]]; then
    if [[ $TARGET =~ ^[0-9a-f]+$ ]]; then
        _MODE="commits"
        _TARGET_TYPE="commit"
    else
        if [[ -e $TARGET ]]; then
            if [[ -f $TARGET ]]; then
                _TARGET_TYPE="file"
            else
                _TARGET_TYPE="directory"
            fi
        else
            echo "Invalid input; please try again"
            showUsage
        fi
    fi
fi

# Only allow line number if the target is a file
if [[ $LINE != "" && $_TARGET_TYPE != "file" ]]; then
    echo "Line number only supported for files; aborting"
    exit 64
fi

# If we're using browse mode and we're in a sub-directory, add the relative path
if [[ $_MODE == "browse" ]]; then
    RPATH=$(git rev-parse --show-prefix)
    if [[ $RPATH != "" ]]; then
        TARGET="$RPATH$TARGET"
        if [[ $_TARGET_TYPE == "empty" ]]; then
            _TARGET_TYPE="directory"
        fi
    fi
fi

# Trim trailing slash if there is one
TARGET="${TARGET%/}"

# If we haven't set a target branch or tag reference, use the current one if possible
if [[ $GIT_COMPLETION != "" ]]; then
    if [[ -e $GIT_COMPLETION ]]; then
        source $GIT_COMPLETION
        if [[ $REF == "" ]]; then
            REF=$(__git_ps1 '%s' | tr -d '()')
        fi
    else
        echo "Warning: \"$GIT_COMPLETION\" does not exist; unable to determine current head reference"
    fi
else
    echo "Warning: No Git completion path set; this is required for automatic head reference detection"
fi

# Build the final URL for the proper service
case $REMOTE_SERVICE in
    github)
    if [[ $_MODE == "browse" ]]; then
        case $_TARGET_TYPE in
            empty)
            if [[ $REF == "master" ]]; then
                REF=""
            fi
            if [[ $REF != "" ]]; then
                MODE="/tree"
            fi
            ;;
            file)
            MODE="/blob"
            ;;
            directory)
            MODE="/tree"
            ;;
        esac
    else
        if [[ $_TARGET_TYPE == "commit" ]]; then
            MODE="/commit"
            REF=""
        else
            MODE="/commits"
        fi
    fi
    if [[ $REF != "" ]]; then
        REF="/$REF"
    fi
    if [[ $TARGET != "" ]]; then
        TARGET="/$TARGET"
    fi
    if [[ $LINE != "" ]]; then
        LINE="#L$LINE"
    fi
    URL="https://github.com/$GROUP/$REPO$MODE$REF$TARGET$LINE"
    ;;
    stash)
    GROUP=$(echo $GROUP | tr [:lower:] [:upper:])
    if [[ $TARGET != "" ]]; then
        TARGET="/$TARGET"
    fi
    if [[ $REF == "master" ]]; then
        REF=""
    fi
    if [[ $REF != "" ]]; then
        REF="?at=$REF"
    fi
    if [[ $LINE != "" ]]; then
        LINE="#$LINE"
    fi
    URL="$STASH_URL_ROOT/projects/$GROUP/repos/$REPO/$_MODE$TARGET$REF$LINE"
    ;;
esac

if [[ $URL_ONLY == true ]]; then
    echo $URL
else
    echo "Opening '$URL'..."
    open $URL
fi
